dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: latest

before_script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-*.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Downloading chrome..."
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

install: ./mvnw -B clean validate

script:
  - ./mvnw -B -Pcheck-duplicate,check-checkstyle,check-cycles,check-cpd,check-pmd,check-spotbugs -DskipTests=true install
#  - /usr/bin/xvfb-run ./mvnw -B -DwebDriverType=firefox verify
  - /usr/bin/xvfb-run ./mvnw -B -DwebDriverType=chrome verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - /usr/bin/xvfb-run ./mvnw org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
